<?php

namespace AppBundle\Repository;

/**
 * NotificacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificacionesRepository extends \Doctrine\ORM\EntityRepository
{
}
