<?php

namespace AppBundle\Repository;

/**
 * TipoParametroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoParametroRepository extends \Doctrine\ORM\EntityRepository
{
}
